[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://searchenginebe-production.up.railway.app/api/:splat"
  status = 200
  force = true

[dev]
  command = "webpack serve --open"
  port = 5000
